import {defineAgent} from './types.js';
export const agentRegistry={
'cto':defineAgent({name:'cto',displayName:'Chief Technology Officer Agent',description:'Meta-agent that dispatches specialists, resolves contradictions, and writes final handoffs.',model:'reasoning',color:'purple',memoryScope:'project',axioms:['Scope is strategy','No recommendation bypasses guardrails','Traceability matters'],commands:['analyze-task','dispatch','handoff'],skills:['orchestrate-task-analysis'],profilePath:'src/profiles/cto.md',outputProtocol:'cto-verdict-v1',canDispatch:true,canImplement:false}),
'agent-2a-operations-classifier':defineAgent({name:'agent-2a-operations-classifier',displayName:'Agent 2A — Operations Classifier',description:'Classifies business operations and finance work into approved categories.',model:'fast',color:'cyan',memoryScope:'session',axioms:['Classify only from evidence','Use standard categories first','Lower confidence when vague'],commands:['classify-task'],skills:['classify-business-task'],profilePath:'src/profiles/agent-2a-operations-classifier.md',outputProtocol:'classification-output-v1',canDispatch:false,canImplement:false}),
'agent-2b-risk-urgency':defineAgent({name:'agent-2b-risk-urgency',displayName:'Agent 2B — Risk and Urgency',description:'Assesses financial risk, urgency, business impact, and human review requirements.',model:'advanced',color:'orange',memoryScope:'session',axioms:['Payment is sensitive','Do not invent exposure','Risk must be explainable'],commands:['assess-risk'],skills:['assess-finance-risk'],profilePath:'src/profiles/agent-2b-risk-urgency.md',outputProtocol:'finance-risk-output-v1',canDispatch:false,canImplement:false}),
'agent-2c-data-quality-context':defineAgent({name:'agent-2c-data-quality-context',displayName:'Agent 2C — Data Quality and Context',description:'Checks missing context and ambiguity before recommendation.',model:'fast',color:'teal',memoryScope:'session',axioms:['Missing fields matter','Do not fill blanks','Ask when needed'],commands:['check-context'],skills:['check-context-quality'],profilePath:'src/profiles/agent-2c-data-quality-context.md',outputProtocol:'context-quality-output-v1',canDispatch:false,canImplement:false}),
'agent-3-recommendation':defineAgent({name:'agent-3-recommendation',displayName:'Agent 3 — Recommendation',description:'Produces recommended owner, priority, next action, and assignment suggestion.',model:'advanced',color:'green',memoryScope:'session',axioms:['One clear next action','Trace to analysis','No approval automation'],commands:['recommend-next-action'],skills:['recommend-next-action'],profilePath:'src/profiles/agent-3-recommendation.md',outputProtocol:'recommendation-output-v1',canDispatch:false,canImplement:false}),
'agent-4-guardrail-confidence':defineAgent({name:'agent-4-guardrail-confidence',displayName:'Agent 4 — Guardrail and Confidence',description:'Validates recommendations, detects unsupported assumptions, adjusts confidence, and flags review.',model:'reasoning',color:'red',memoryScope:'audit',axioms:['No bypass','Unsupported facts are flagged','Confidence is not certainty'],commands:['guardrail-check'],skills:['hallucination-guard'],profilePath:'src/profiles/agent-4-guardrail-confidence.md',outputProtocol:'guardrail-output-v1',canDispatch:false,canImplement:false}),
'deep-qa':defineAgent({name:'deep-qa',displayName:'Deep QA',description:'Quality sentinel for backend, frontend, agent runtime, schemas, protocols, tests, and architecture drift. Does not implement fixes.',model:'reasoning',color:'green',memoryScope:'project',axioms:['Evidence not opinion','Severity is objective','Root cause not symptoms','Positives matter'],commands:['audit-backend','audit-frontend','audit-agent-runtime'],skills:['quality-audit'],profilePath:'src/profiles/deep-qa.md',outputProtocol:'qa-audit-v1',canDispatch:false,canImplement:false})
} as const;
