import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID}from'node:crypto';import {AgentMessageSchema,type AgentMessage}from'@orqestra/schemas';import{skillRegistry}from'./skills.js';
const dir=process.env.ORQESTRA_RUNTIME_DIR??'packages/agents/runtime';
export const paths={inbox:(a:string)=>path.join(dir,'inbox',`${a}.jsonl`),session:(s:string)=>path.join(dir,'sessions',s),transcript:(s:string)=>path.join(dir,'sessions',s,'transcript.jsonl'),handoff:(s:string)=>path.join(dir,'sessions',s,'handoff.md'),latest:()=>path.join(dir,'latest-session.txt')};
export async function sendMessage(m:AgentMessage){AgentMessageSchema.parse(m);const inbox=paths.inbox(m.toAgent);await fs.mkdir(path.dirname(inbox),{recursive:true});await fs.appendFile(inbox,JSON.stringify(m)+'
');const t=paths.transcript(m.sessionId);await fs.mkdir(path.dirname(t),{recursive:true});await fs.appendFile(t,JSON.stringify(m)+'
')}
export async function readInbox(agent:string){try{return (await fs.readFile(paths.inbox(agent),'utf8')).split('
').filter(Boolean).map(l=>AgentMessageSchema.parse(JSON.parse(l)))}catch(e:any){if(e.code==='ENOENT')return[];throw e}}
export async function createSession(objective:string){const id=`session_${randomUUID()}`;await fs.mkdir(paths.session(id),{recursive:true});await fs.writeFile(path.join(paths.session(id),'objective.txt'),objective);await fs.writeFile(paths.latest(),id);return id}
export async function resolveSession(id:string){if(id!=='latest')return id;return(await fs.readFile(paths.latest(),'utf8')).trim()}
export async function runAgent(agent:string){const pending=(await readInbox(agent)).filter(m=>m.status==='PENDING');for(const m of pending){const name=m.content.skillName as string;const skill=skillRegistry[name];if(!skill){await sendMessage({messageId:randomUUID(),sessionId:m.sessionId,fromAgent:agent,toAgent:m.fromAgent,type:'RESULT',task:`Failed: ${m.task}`,content:{error:`Unknown skill ${name}`},status:'FAILED',createdAt:new Date().toISOString()});continue}const input=skill.inputSchema.parse(m.content.input);const output=skill.outputSchema.parse(skill.runMock(input));await sendMessage({messageId:randomUUID(),sessionId:m.sessionId,fromAgent:agent,toAgent:m.fromAgent,type:'RESULT',task:`Result for ${m.task}`,content:{skillName:name,output},confidenceScore:typeof output.confidenceScore==='number'?output.confidenceScore:typeof output.finalConfidenceScore==='number'?output.finalConfidenceScore:undefined,status:'COMPLETE',createdAt:new Date().toISOString()})}}
export async function writeHandoff(sessionId:string){const raw=await fs.readFile(paths.transcript(sessionId),'utf8');const msgs=raw.split('
').filter(Boolean).map(l=>JSON.parse(l));const results=msgs.filter((m:any)=>m.type==='RESULT');const content=['# OrqestraAI Handoff','',`## Session
${sessionId}`,'','## Completed',...results.map((m:any)=>`- ${m.fromAgent}: ${m.task}`),'','## Next Steps','- Review guardrail output before acting.','- Persist approved recommendations through backend API.','- Run deep-qa before merge.',''].join('
');await fs.writeFile(paths.handoff(sessionId),content);return paths.handoff(sessionId)}
export async function dispatch(sessionId:string,toAgent:string,skillName:string,input:any){await sendMessage({messageId:randomUUID(),sessionId,fromAgent:'cto',toAgent,type:'DISPATCH',task:`Run ${skillName}`,content:{skillName,input},status:'PENDING',createdAt:new Date().toISOString()})}
